### login request to example server
POST http://localhost:3000/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "admin1234",
  "password": "admin1234#"
}

### registration request to example server
POST http://localhost:3000/auth/register
Content-Type: application/json
Accept: application/json

{
  "username": "admin1234",
  "password": "admin1234#",
  "email": "admin1234@gmail.com"
}

### registration request to example server
GET http://localhost:3000/auth/validate
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjEyMzQiLCJpYXQiOjE3NDQwMDc3OTUsImV4cCI6MTc0NDA5NDE5NX0.AoQAoIIb0g6bD4WxMnfAx3hqczaETa6EOVwdzst1P5w



### CREATE PATIENT
POST http://localhost:3000/api/patients
Accept: application/json
Content-Type: application/json

{
  "name": "John Doe",
  "address": "123 Main St, Springfield, USA",
  "email": "john.dossse@example.com",
  "dateOfBirth": "1990-05-15",
  "gender": "Male"
}


### GET PATIENTS
GET http://localhost:3000/api/patients
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjEyMzQiLCJpYXQiOjE3NTIzNDI4MzcsImV4cCI6MTc1MjM0MzczN30.YRgggOAlfoXTFOazpyaE61PoUSjHZET6lNgVzrWbSxo


### GET PATIENT by ID
GET http://localhost:3000/api/patients/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjEyMzQiLCJpYXQiOjE3NTIzMzgyNjAsImV4cCI6MTc1MjMzOTE2MH0.TJDpFXyTkuXjuPzkFFVMDwebDiiAUzjRbmqyxB4rk2E


### UPDATE PATIENT BY ID
PUT http://localhost:3000/api/patients/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjEyMzQiLCJpYXQiOjE3NTIzMzgyNjAsImV4cCI6MTc1MjMzOTE2MH0.TJDpFXyTkuXjuPzkFFVMDwebDiiAUzjRbmqyxB4rk2E

{
  "name": "Jessica",
  "address": "123 Main St, Springfield, USA",
  "email": "jessica.doe@example.com",
  "dateOfBirth": "1990-05-15",
  "gender": "Girl"
}

### DELETE PATIENTS
DELETE http://localhost:3000/api/patients/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjEyMzQiLCJpYXQiOjE3NTIzMzgyNjAsImV4cCI6MTc1MjMzOTE2MH0.TJDpFXyTkuXjuPzkFFVMDwebDiiAUzjRbmqyxB4rk2E



###
GET http://localhost:3000/api/billing
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjEyMzQiLCJpYXQiOjE3NTIzMzgyNjAsImV4cCI6MTc1MjMzOTE2MH0.TJDpFXyTkuXjuPzkFFVMDwebDiiAUzjRbmqyxB4rk2E


### testing
POST http://localhost:3000/api/billing
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjEyMzQiLCJpYXQiOjE3NTIzMzgyNjAsImV4cCI6MTc1MjMzOTE2MH0.TJDpFXyTkuXjuPzkFFVMDwebDiiAUzjRbmqyxB4rk2E

{
  "patientId": 1,
  "name": "jamal",
  "email": "jamal@gmail.com"
}

###
GRPC localhost:9091/BillingService/CreateBillingAccount
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjEyMzQiLCJpYXQiOjE3NTIzMzgyNjAsImV4cCI6MTc1MjMzOTE2MH0.TJDpFXyTkuXjuPzkFFVMDwebDiiAUzjRbmqyxB4rk2E

{
  "patientId": 1,
  "name": "jamal",
  "email": "jamal@gmail.com"
}
