### login request to example server
POST http://localhost:8083/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "admin1234",
  "password": "admin1234#"
}

### registration request to example server
POST http://localhost:8083/auth/register
Content-Type: application/json
Accept: application/json

{
  "username": "admin1234",
  "password": "admin1234#",
  "email": "admin1234@gmail.com"
}

### registration request to example server
GET http://localhost:8083/auth/validate
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjEyMzQiLCJpYXQiOjE3NTIzMzYwNzEsImV4cCI6MTc1MjMzNjk3MX0.fODWUZu5t6GEIknn1f2EI0xoGfXWmAHt5vYrrvYR2xs
